//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public int TaskId { get; set; }
        public string Name { get; set; }
        public int UserId { get; set; }
        public string Description { get; set; }
        public long Deadline { get; set; }
        public int StoryId { get; set; }
        public int Status { get; set; }
    
        public virtual User User { get; set; }
        public virtual Story Story { get; set; }
    }
}
